[build]
  command = "npm ci --prefer-offline --no-audit && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.5.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_CONFIG_LOGLEVEL = "error"
  NPM_CONFIG_PROGRESS = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
